kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: demo:v1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /api/values
            port: 80
        readinessProbe:
          httpGet:
            path: /api/values
            port: 80
---
kind: Service
apiVersion: v1
metadata:
  name:  demo-api-service
spec:
  selector:
    app:  demo
  type:  LoadBalancer
  ports:
  - protocol: TCP
    port:  80
    targetPort:  80