kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: backend-deployment-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 25