kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 81
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /api/values/1
            port: 81
        readinessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /api/values/1
            port: 81