kind: Service
apiVersion: v1
metadata:
  name:  demo-backend-service
spec:
  selector:
    app:  demo-backend
  type:  LoadBalancer
  ports:
  - protocol: TCP
    port:  81
    targetPort:  81
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
      - name: backend
        image: backend:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 81
        livenessProbe:
          httpGet:
            path: /api/values
            port: 81
        readinessProbe:
          httpGet:
            path: /api/values
            port: 81